{% set name = "clean-text" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clean-text-{{ version }}.tar.gz
  sha256: 8a45df013c4b58a7f367d3264265cabe00a3cc918f27fbb3cb8492ed6b940d9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<3.9
    - poetry
  run:
    - emoji
    - ftfy >=6.0
    - python >=3.5,<3.9
    - unicode

test:
  imports:
    - cleantext
    - unicode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/clean-text/
  summary: Functions to preprocess and normalize text.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
