{% set name = "clean-text" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 44805f001bba23467a0f993f1144b51823d66c5284f18574d4ac08594bffbf42

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<3.9
    - poetry
  run:
    - emoji
    - ftfy >=5.8,<6.0
    - python >=3.5,<3.9

test:
  imports:
    - cleantext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/clean-text/
  summary: Functions to preprocess and normalize text.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
