{% set name = "clean-text" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clean-text-{{ version }}.tar.gz
  sha256: e525951bef0c8b72e03c987fdac2c475b61d7debf7a8834366fd75716179b6e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<3.9
    - poetry
  run:
    - emoji
    - ftfy >=5.8,<6.0
    - python >=3.5,<3.9

test:
  imports:
    - cleantext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/clean-text/
  summary: Functions to preprocess and normalize text.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
